name: 'Build packages'
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  # build-packages:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: ./build/get_external_dependencies.sh
  #     - run: ./build/setup.sh bbb-apps-akka
  #     - run: ./build/setup.sh bbb-config
  #     - run: ./build/setup.sh bbb-etherpad
  #     - run: ./build/setup.sh bbb-freeswitch-core
  #     - run: ./build/setup.sh bbb-freeswitch-sounds
  #     - run: ./build/setup.sh bbb-fsesl-akka
  #     - run: ./build/setup.sh bbb-html5
  #     - run: ./build/setup.sh bbb-learning-dashboard
  #     - run: ./build/setup.sh bbb-libreoffice-docker
  #     - run: ./build/setup.sh bbb-mkclean
  #     - run: ./build/setup.sh bbb-pads
  #     - run: ./build/setup.sh bbb-playback
  #     - run: ./build/setup.sh bbb-playback-notes
  #     - run: ./build/setup.sh bbb-playback-podcast
  #     - run: ./build/setup.sh bbb-playback-presentation
  #     - run: ./build/setup.sh bbb-playback-screenshare
  #     - run: ./build/setup.sh bbb-record-core
  #     - run: ./build/setup.sh bbb-web
  #     - run: ./build/setup.sh bbb-webrtc-sfu
  #     - run: ./build/setup.sh bigbluebutton
  #     - run: tar cvf artifacts.tar artifacts/
  #     - name: Archive packages
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: artifacts.tar
  #         path: |
  #           artifacts.tar

  # fake the build (to quickly test the setup instructions)
  build-packages:
    steps:
        - run: |
            sudo sh -c '
            echo "Faking a package build (to speed up installation test)"
            cd /
            wget -q "http://ci.bbbvm.imdt.com.br/artifacts.tar"
            tar xf artifacts.tar
            '
  ssl-create-ca:
    steps:
        - run: |
            sudo sh -c '
            mkdir ~/bbb-docker-dev-setup/
            cd ~/bbb-docker-dev-setup/

            openssl rand -base64 48 > bbb-dev-ca.pass ;
            chmod 600 bbb-dev-ca.pass ;
            openssl genrsa -des3 -out bbb-dev-ca.key -passout file:bbb-dev-ca.pass 2048 ;

            openssl req -x509 -new -nodes -key bbb-dev-ca.key -sha256 -days 1460 -passin file:bbb-dev-ca.pass -out bbb-dev-ca.crt -subj "/C=CA/ST=BBB/L=BBB/O=BBB/OU=BBB/CN=BBB-DEV" ;
            '
  ssl-trust-ca:
    steps:
        - run: |
            sudo sh -c '
            sudo mkdir /usr/local/share/ca-certificates/bbb-dev/
            sudo cp ~/bbb-docker-dev-setup/bbb-dev-ca.crt /usr/local/share/ca-certificates/bbb-dev/
            sudo chmod 644 /usr/local/share/ca-certificates/bbb-dev/bbb-dev-ca.crt
            sudo update-ca-certificates

            '
  ssl-generate-certificate:
    steps:
        - run: |
            sudo sh -c '
            cd ~/bbb-docker-dev-setup/
            echo "127.0.0.1 bbb-ci.test" >> /etc/hosts
            openssl genrsa -out bbb-ci.test.key 2048
            rm bbb-ci.test.csr bbb-ci.test.crt bbb-ci.test.key
            cat > bbb-ci.test.ext << EOF
            authorityKeyIdentifier=keyid,issuer
            basicConstraints=CA:FALSE
            keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
            subjectAltName = @alt_names
            [alt_names]
            DNS.1 = bbb-ci.test
            EOF

            openssl req -nodes -newkey rsa:2048 -keyout bbb-ci.test.key -out bbb-ci.test.csr -subj "/C=CA/ST=BBB/L=BBB/O=BBB/OU=BBB/CN=bbb-ci.test" -addext "subjectAltName = DNS:bbb-ci.test" 

            openssl x509 -req -in bbb-ci.test.csr -CA bbb-dev-ca.crt -CAkey bbb-dev-ca.key -CAcreateserial -out bbb-ci.test.crt -days 825 -sha256 -passin file:bbb-dev-ca.pass -extfile bbb-ci.test.ext
            cd

            mkdir /certs/
            cp ~/bbb-docker-dev-setup/bbb-dev-ca.crt /certs/
            cat ~/bbb-docker-dev-setup/$HOSTNAME.crt > /certs/fullchain.pem
            cat ~/bbb-docker-dev-setup/bbb-dev-ca.crt >> /certs/fullchain.pem
            cat ~/bbb-docker-dev-setup/$HOSTNAME.key > /certs/privkey.pem

            '
  install-from-packages:
    runs-on: ubuntu-20.04
    needs: build-packages
    steps:
      - run: |
          sudo sh -c '
          apt install -yq dpkg-dev
          apt --purge -y remove apache2-bin
          cd /root && wget -q http://ci.bbbvm.imdt.com.br/cache-3rd-part-packages.tar
          cd /artifacts && tar xf /root/cache-3rd-part-packages.tar
          cd /artifacts && dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz
          echo "deb [trusted=yes] file:/artifacts/ ./" >> /etc/apt/sources.list
          cd /root/ && wget -q https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh -O bbb-install.sh
          cat bbb-install.sh | sed "s|> /etc/apt/sources.list.d/bigbluebutton.list||g" | bash -s -- -v focal-25-dev -s bbb-ci.test -d /certs/
          '