pipeline {
    agent {
        docker { image 'node:14-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'ls -l'
                sh 'pwd'
                echo 'HTML5 dir'
                sh 'cat bigbluebutton-html5/temp'
            }
        }
    }
}
